In [2]:
# Run this in a Colab cell to set up SQLite from your Excel file
import pandas as pd
import sqlite3

df = pd.read_csv('/content/cleaned_dataset.csv')
conn = sqlite3.connect('orders.db')
df.to_sql('orders', conn, if_exists='replace', index=False)

1200

In [3]:
def run_query(sql):
    result = pd.read_sql_query(sql, conn)
    print(result.to_string(index=False))
    return result

***SELECT Queries***

In [6]:
run_query("SELECT * FROM orders LIMIT 5")

  OrderID       Date CustomerID Product  Quantity  UnitPrice ShippingAddress PaymentMethod OrderStatus TrackingNumber  ItemsInCart CouponCode ReferralSource  TotalPrice
ORD200000 2023-01-04     C72649 Monitor         5     570.62     928 Main St    Debit Card     Shipped    TRK37947903            7     SAVE10      Instagram     2853.10
ORD200001 2024-08-23     C75739   Phone         2     151.35     823 Main St        Online     Shipped    TRK91186779            3     SAVE10       Referral      302.70
ORD200002 2024-02-27     C81728  Tablet         5     550.68     512 Main St   Credit Card   Cancelled    TRK42903982            8   FREESHIP          Email     2753.40
ORD200003 2023-10-15     C33540   Chair         1     273.19     275 Main St    Debit Card    Returned    TRK62788070            5     SAVE10       Facebook      273.19
ORD200004 2025-05-08     C81840 Printer         4     626.01     668 Main St        Online   Delivered    TRK29241424            8     SAVE10          Email     2504.04

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

The orders table has 14 columns including OrderID, Date, CustomerID,
Product, Quantity, UnitPrice, PaymentMethod, OrderStatus, and TotalPrice.
The dataset contains 1,200 orders spanning from 2023 to 2025.

In [7]:
run_query("""SELECT OrderID, Product, TotalPrice, OrderStatus
FROM orders
LIMIT 5""")

  OrderID Product  TotalPrice OrderStatus
ORD200000 Monitor     2853.10     Shipped
ORD200001   Phone      302.70     Shipped
ORD200002  Tablet     2753.40   Cancelled
ORD200003   Chair      273.19    Returned
ORD200004 Printer     2504.04   Delivered

     OrderID  Product  TotalPrice OrderStatus
0  ORD200000  Monitor     2853.10     Shipped
1  ORD200001    Phone      302.70     Shipped
2  ORD200002   Tablet     2753.40   Cancelled
3  ORD200003    Chair      273.19    Returned
4  ORD200004  Printer     2504.04   Delivered

Selecting key columns shows a mix of products and statuses across orders.
Not all orders are successful — Cancelled and Returned statuses appear
alongside Shipped and Delivered ones.

 ***Filter with WHERE***

In [ ]:
run_query("""SELECT * FROM orders
WHERE OrderStatus = 'Delivered'""")

  OrderID                Date CustomerID Product  Quantity  UnitPrice ShippingAddress PaymentMethod OrderStatus TrackingNumber  ItemsInCart CouponCode ReferralSource  TotalPrice
ORD200004 2025-05-08 00:00:00     C81840 Printer         4     626.01     668 Main St        Online   Delivered    TRK29241424            8     SAVE10          Email     2504.04
ORD200015 2023-07-17 00:00:00     C39416 Printer         1     473.96     942 Main St          Cash   Delivered    TRK54930938            3       None         Google      473.96
ORD200021 2024-11-17 00:00:00     C99023 Monitor         4     342.95     569 Main St          Cash   Delivered    TRK52646983            6       None         Google     1371.80
ORD200024 2024-10-30 00:00:00     C17470  Laptop         2     230.95     956 Main St        Online   Delivered    TRK28775057            3   WINTER15       Referral      461.90
ORD200025 2024-07-24 00:00:00     C42577 Monitor         1     399.98     709 Main St    Debit Card   Delivered    TRK69423327            3   WINTER15          Email      399.98
ORD200026 2024-03-06 00:00:00     C21944  Laptop         5      59.55     296 Main St        Online   Delivered    TRK80276812            6       None       Referral      297.75
ORD200029 2024-09-20 00:00:00     C33260    Desk         3     423.53     930 Main St   Credit Card   Delivered    TRK59744090            6     SAVE10       Referral     1270.59
ORD200032 2023-05-01 00:00:00     C12388  Tablet         5     536.72     830 Main St          Cash   Delivered    TRK99261395           10       None          Email     2683.60
ORD200038 2024-12-19 00:00:00     C15924  Laptop         1     245.89     549 Main St    Debit Card   Delivered    TRK14835975            3     SAVE10         Google      245.89
ORD200039 2025-02-27 00:00:00     C96664 Printer         3     256.46     666 Main St   Credit Card   Delivered    TRK85508960            4     SAVE10       Referral      769.38
ORD200040 2023-08-20 00:00:00     C84766    Desk         2     344.02     267 Main St        Online   Delivered    TRK78967923            4   FREESHIP      Instagram      688.04
ORD200061 2024-03-24 00:00:00     C61618    Desk         4     122.20     104 Main St          Cash   Delivered    TRK43458485            7   FREESHIP       Facebook      488.80
ORD200065 2023-12-30 00:00:00     C97735 Monitor         5      81.70     385 Main St   Credit Card   Delivered    TRK13743703            6       None      Instagram      408.50
ORD200075 2023-09-26 00:00:00     C80651  Tablet         3     398.17     917 Main St    Debit Card   Delivered    TRK14846720            5     SAVE10          Email     1194.51
ORD200078 2024-08-06 00:00:00     C32029 Printer         4     175.36     146 Main St    Debit Card   Delivered    TRK68535532            4   FREESHIP      Instagram      701.44
ORD200085 2024-09-09 00:00:00     C14553  Tablet         3     146.73     768 Main St          Cash   Delivered    TRK93538334            8   FREESHIP          Email      440.19
ORD200090 2023-09-18 00:00:00     C36540   Chair         4     182.08     611 Main St     Gift Card   Delivered    TRK35828122            4     SAVE10          Email      728.32
ORD200096 2024-06-01 00:00:00     C93007   Phone         2     232.83     103 Main St     Gift Card   Delivered    TRK85696091            7       None      Instagram      465.66
ORD200100 2023-02-17 00:00:00     C74866   Phone         3     664.79     743 Main St        Online   Delivered    TRK53783265            6       None       Facebook     1994.37
ORD200104 2024-07-30 00:00:00     C65744   Phone         1     582.04     647 Main St     Gift Card   Delivered    TRK39906058            1   FREESHIP          Email      582.04
ORD200108 2024-12-28 00:00:00     C33099  Laptop         5      48.38     522 Main St     Gift Card   Delivered    TRK28522330            9   WINTER15          Email      241.90
ORD200123 2023-07-06 00:00:00     C86064    Desk         3     278.04     727 Main St        Online   Delivered    TRK62182901            5       None      Instagram      834.12
ORD200128 2023-02-17 00:00:00     C86408  Tablet         4      21.07     244 Main St     Gift Card   Delivered    TRK41432648            4   FREESHIP         Google       84.28
ORD200137 2024-11-26 00:00:00     C50682 Monitor         2     250.98     598 Main St   Credit Card   Delivered    TRK12242337            5       None         Google      501.96
ORD200140 2025-05-31 00:00:00     C33110   Chair         3     528.14     388 Main St        Online   Delivered    TRK38624225            3   FREESHIP          Email     1584.42
ORD200145 2024-03-02 00:00:00     C85929 Printer         3     146.91     798 Main St   Credit Card   Delivered    TRK29318610            6   FREESHIP         Google      440.73
ORD200149 2023-12-27 00:00:00     C39671  Laptop         1     217.56     174 Main St    Debit Card   Delivered    TRK47153818            3       None       Facebook      217.56
ORD200156 2024-11-08 00:00:00     C58808   Chair         2     269.83     651 Main St        Online   Delivered    TRK24451893            4     SAVE10          Email      539.66
ORD200166 2025-03-04 00:00:00     C28889   Chair         3      86.29     565 Main St          Cash   Delivered    TRK23791726            6   WINTER15      Instagram      258.87
ORD200169 2024-04-07 00:00:00     C35785 Printer         1     427.82     732 Main St        Online   Delivered    TRK78923089            2   WINTER15          Email      427.82
ORD200171 2023-08-15 00:00:00     C20448  Tablet         2     148.22     336 Main St   Credit Card   Delivered    TRK67379895            7   WINTER15      Instagram      296.44
ORD200172 2025-04-06 00:00:00     C34134 Printer         1     254.12     365 Main St        Online   Delivered    TRK43074303            1   WINTER15          Email      254.12
ORD200173 2024-03-24 00:00:00     C95901   Phone         3     664.46     806 Main St        Online   Delivered    TRK56989066            4   FREESHIP         Google     1993.38
ORD200174 2024-04-16 00:00:00     C51145 Printer         4     600.81     790 Main St    Debit Card   Delivered    TRK59154274            9     SAVE10          Email     2403.24
ORD200178 2024-04-11 00:00:00     C53070   Chair         4     512.06     283 Main St        Online   Delivered    TRK49791755            5     SAVE10         Google     2048.24
ORD200179 2024-11-24 00:00:00     C27401  Laptop         3     539.91     500 Main St   Credit Card   Delivered    TRK14332053            8       None          Email     1619.73
ORD200183 2024-04-18 00:00:00     C39246 Monitor         5     186.28     258 Main St    Debit Card   Delivered    TRK16658182            8     SAVE10          Email      931.40
ORD200196 2025-01-24 00:00:00     C40882    Desk         4     217.13     719 Main St          Cash   Delivered    TRK64165503            8   WINTER15          Email      868.52
ORD200200 2025-06-07 00:00:00     C97681  Tablet         5     433.26     895 Main St   Credit Card   Delivered    TRK37531040            9     SAVE10         Google     2166.30
ORD200207 2025-03-18 00:00:00     C54595   Phone         1     121.96     999 Main St    Debit Card   Delivered    TRK44416659            3       None         Google      121.96
ORD200210 2024-12-05 00:00:00     C93821   Chair         3     358.48     513 Main St     Gift Card   Delivered    TRK10658539            7   FREESHIP       Facebook     1075.44
ORD200214 2024-08-21 00:00:00     C29483    Desk         4     305.72     673 Main St        Online   Delivered    TRK89423603            5       None       Facebook     1222.88
ORD200219 2025-05-02 00:00:00     C48946  Laptop         5      61.97     457 Main St          Cash   Delivered    TRK99387220            6     SAVE10          Email      309.85
ORD200226 2025-06-27 00:00:00     C31501    Desk         3     588.05     242 Main St     Gift Card   Delivered    TRK93063929            8       None      Instagram     1764.15
ORD200229 2025-03-28 00:00:00     C62622  Tablet         1     562.61     762 Main St   Credit Card   Delivered    TRK70997648            3   WINTER15       Facebook      562.61
ORD200230 2023-12-16 00:00:00     C94595    Desk         4      61.91     948 Main St     Gift Card   Delivered    TRK24497305            6   WINTER15          Email      247.64
ORD200254 2023-12-26 00:00:00     C10866 Monitor         3     263.19     770 Main St        Online   Delivered    TRK34809583            5       None      Instagram      789.57
ORD200259 2023-06-11 00:00:00     C20977   Chair         4     435.12     636 Main St   Credit Card   Delivered    TRK54991561            9     SAVE10      Instagram     1740.48
ORD200261 2025-05-28 00:00:00     C68976   Phone         5     173.65     460 Main St     Gift Card   Delivered    TRK25491356            9     SAVE10          Email      868.25
ORD200267 2025-04-17 00:00:00     C84480   Chair         5     468.51     803 Main St    Debit Card   Delivered    TRK62361867            9       None       Facebook     2342.55
ORD200268 2023-08-11 00:00:00     C37032   Phone         2     423.88     655 Main St    Debit Card   Delivered    TRK48639226            7     SAVE10       Referral      847.76
ORD200277 2024-09-09 00:00:00     C11210   Chair         5      90.92     910 Main St   Credit Card   Delivered    TRK44929965            9     SAVE10       Facebook      454.60
ORD200278 2024-11-18 00:00:00     C46015  Laptop         5     362.46     299 Main St          Cash   Delivered    TRK46598430            6   FREESHIP      Instagram     1812.30
ORD200280 2023-03-27 00:00:00     C55388  Tablet         3     404.62     740 Main St     Gift Card   Delivered    TRK75741001            6   FREESHIP      Instagram     1213.86
ORD200285 2025-06-10 00:00:00     C67583   Phone         1     338.31     974 Main St        Online   Delivered    TRK93281700            3       None         Google      338.31
ORD200290 2023-05-05 00:00:00     C24901   Chair         3      99.90     258 Main St          Cash   Delivered    TRK14029489            8   FREESHIP       Facebook      299.70
ORD200291 2024-05-12 00:00:00     C61521   Phone         2     345.01     670 Main St   Credit Card   Delivered    TRK93676567            6   FREESHIP         Google      690.02
ORD200292 2025-01-15 00:00:00     C39639 Monitor         1      65.95     185 Main St   Credit Card   Delivered    TRK31042152            5       None       Facebook       65.95
ORD200304 2024-10-18 00:00:00     C86762 Monitor         5     408.73     326 Main St     Gift Card   Delivered    TRK75686292           10   FREESHIP      Instagram     2043.65
ORD200307 2023-07-01 00:00:00     C92407  Laptop         3     557.41     135 Main St        Online   Delivered    TRK11755610            4       None          Email     1672.23
ORD200309 2023-10-03 00:00:00     C63153   Chair         4     549.76     625 Main St    Debit Card   Delivered    TRK38033305            4   FREESHIP       Facebook     2199.04
ORD200313 2023-07-09 00:00:00     C67687   Chair         2     434.30     978 Main St          Cash   Delivered    TRK22838735            7     SAVE10      Instagram      868.60
ORD200314 2023-10-04 00:00:00     C29931    Desk         4     153.09     540 Main St        Online   Delivered    TRK48712417            4   FREESHIP       Referral      612.36
ORD200322 2024-06-14 00:00:00     C48646   Phone         5     231.82     339 Main St    Debit Card   Delivered    TRK18233748            6     SAVE10       Facebook     1159.10
ORD200331 2023-04-15 00:00:00     C78724 Printer         3     422.13     187 Main St        Online   Delivered    TRK25703134            7     SAVE10       Facebook     1266.39
ORD200334 2024-03-26 00:00:00     C90348   Chair         4     224.75     728 Main St        Online   Delivered    TRK20635777            7   WINTER15       Facebook      899.00
ORD200349 2023-11-30 00:00:00     C39648   Chair         1     465.33     824 Main St     Gift Card   Delivered    TRK56016905            2   FREESHIP         Google      465.33
ORD200351 2025-02-15 00:00:00     C94248  Laptop         1      64.66     494 Main St    Debit Card   Delivered    TRK89406816            4       None      Instagram       64.66
ORD200353 2025-03-28 00:00:00     C16012  Tablet         1     630.82     171 Main St        Online   Delivered    TRK15195225            5   FREESHIP         Google      630.82
ORD200357 2023-07-08 00:00:00     C74982  Laptop         5     408.56     398 Main St    Debit Card   Delivered    TRK98700702            8   FREESHIP      Instagram     2042.80
ORD200359 2023-06-09 00:00:00     C95643    Desk         4     606.57     303 Main St    Debit Card   Delivered    TRK23286689            5   WINTER15       Referral     2426.28
ORD200361 2024-06-29 00:00:00     C53464 Printer         5     659.85     197 Main St   Credit Card   Delivered    TRK32743531            9     SAVE10       Facebook     3299.25
ORD200385 2023-10-31 00:00:00     C56851   Chair         5     191.63     752 Main St     Gift Card   Delivered    TRK65290904            6   FREESHIP       Facebook      958.15
ORD200390 2023-07-14 00:00:00     C55996 Printer         5     508.69     885 Main St          Cash   Delivered    TRK30547638           10   FREESHIP         Google     2543.45
ORD200392 2024-02-28 00:00:00     C95100   Phone         1     627.20     197 Main St        Online   Delivered    TRK47366265            1   WINTER15          Email      627.20
ORD200395 2025-04-25 00:00:00     C30010   Phone         3     127.41     830 Main St     Gift Card   Delivered    TRK35386084            7     SAVE10       Referral      382.23
ORD200404 2023-03-09 00:00:00     C45482 Monitor         2      99.10     440 Main St          Cash   Delivered    TRK54571699            6       None      Instagram      198.20
ORD200409 2023-06-28 00:00:00     C45187    Desk         5      84.13     767 Main St        Online   Delivered    TRK12320793            9     SAVE10         Google      420.65
ORD200413 2023-10-08 00:00:00     C13923  Tablet         1     118.80     123 Main St        Online   Delivered    TRK87598790            6     SAVE10          Email      118.80
ORD200414 2025-05-04 00:00:00     C11829    Desk         2     139.57     797 Main St          Cash   Delivered    TRK84229257            4   WINTER15       Facebook      279.14
ORD200437 2024-04-18 00:00:00     C63378   Phone         1     512.39     955 Main St        Online   Delivered    TRK20863705            2   FREESHIP      Instagram      512.39
ORD200445 2024-03-23 00:00:00     C94569   Phone         1     487.21     227 Main St          Cash   Delivered    TRK31351770            3     SAVE10       Referral      487.21
ORD200446 2023-10-18 00:00:00     C89592  Laptop         5     509.58     262 Main St        Online   Delivered    TRK49442402            6   FREESHIP      Instagram     2547.90
ORD200466 2023-07-18 00:00:00     C37412   Phone         1     432.47     895 Main St          Cash   Delivered    TRK97829604            4   FREESHIP       Referral      432.47
ORD200468 2025-06-21 00:00:00     C90110   Phone         1     418.36     998 Main St   Credit Card   Delivered    TRK60203957            5   FREESHIP          Email      418.36
ORD200481 2023-04-23 00:00:00     C94568  Laptop         4     484.85     317 Main St    Debit Card   Delivered    TRK58653915            5   WINTER15       Referral     1939.40
ORD200508 2025-05-14 00:00:00     C39550   Phone         1     558.27     976 Main St        Online   Delivered    TRK24120267            1       None       Referral      558.27
ORD200510 2024-12-16 00:00:00     C72533 Printer         1     376.76     389 Main St    Debit Card   Delivered    TRK51288986            5     SAVE10          Email      376.76
ORD200511 2024-03-15 00:00:00     C11415 Monitor         5     575.24     267 Main St          Cash   Delivered    TRK65061457            7   WINTER15          Email     2876.20
ORD200531 2024-07-02 00:00:00     C64502    Desk         5     320.01     722 Main St     Gift Card   Delivered    TRK14914388            6       None       Referral     1600.05
ORD200532 2025-05-03 00:00:00     C47365  Laptop         2      41.00     369 Main St        Online   Delivered    TRK42207882            7       None          Email       82.00
ORD200537 2025-03-23 00:00:00     C68553  Tablet         3     247.47     385 Main St        Online   Delivered    TRK58218971            4     SAVE10       Facebook      742.41
ORD200539 2025-02-18 00:00:00     C53277    Desk         3     531.72     473 Main St     Gift Card   Delivered    TRK17653832            7     SAVE10         Google     1595.16
ORD200547 2023-08-20 00:00:00     C40427   Phone         1     613.98     411 Main St        Online   Delivered    TRK25392280            4   FREESHIP       Facebook      613.98
ORD200548 2024-01-05 00:00:00     C17103 Printer         3     426.12     922 Main St        Online   Delivered    TRK64398650            5   WINTER15      Instagram     1278.36
ORD200551 2023-05-18 00:00:00     C23947  Laptop         1     120.98     353 Main St    Debit Card   Delivered    TRK74812710            6   WINTER15          Email      120.98
ORD200558 2024-07-16 00:00:00     C76766   Phone         4     628.12     485 Main St        Online   Delivered    TRK32052962            6   WINTER15      Instagram     2512.48
ORD200568 2023-03-10 00:00:00     C29072  Laptop         2     343.99     312 Main St        Online   Delivered    TRK72334047            4       None         Google      687.98
ORD200578 2024-10-10 00:00:00     C50415 Monitor         5     566.07     587 Main St   Credit Card   Delivered    TRK41345634            6     SAVE10      Instagram     2830.35
ORD200580 2023-11-14 00:00:00     C71076 Monitor         2     255.99     340 Main St   Credit Card   Delivered    TRK65148292            4     SAVE10      Instagram      511.98
ORD200581 2024-11-11 00:00:00     C44674  Laptop         1     627.34     942 Main St        Online   Delivered    TRK87158684            1       None       Referral      627.34
ORD200583 2025-06-15 00:00:00     C27072   Chair         3     154.37     996 Main St     Gift Card   Delivered    TRK29750379            4       None      Instagram      463.11
ORD200584 2025-03-21 00:00:00     C15257   Chair         4     145.05     626 Main St        Online   Delivered    TRK28779938            6     SAVE10         Google      580.20
ORD200587 2023-06-12 00:00:00     C18820 Monitor         5     514.60     347 Main St     Gift Card   Delivered    TRK91547425           10   FREESHIP      Instagram     2573.00
ORD200588 2024-12-10 00:00:00     C61849 Monitor         4     577.82     811 Main St   Credit Card   Delivered    TRK47613918            9       None         Google     2311.28
ORD200589 2025-02-10 00:00:00     C84041  Laptop         2     500.80     900 Main St          Cash   Delivered    TRK84920444            3   FREESHIP       Referral     1001.60
ORD200604 2025-06-22 00:00:00     C99214   Chair         3      32.62     252 Main St    Debit Card   Delivered    TRK81368481            6       None       Facebook       97.86
ORD200621 2023-10-22 00:00:00     C37455   Phone         5     476.01     146 Main St   Credit Card   Delivered    TRK82685594            7   WINTER15         Google     2380.05
ORD200624 2024-01-16 00:00:00     C25967  Tablet         5     341.96     747 Main St    Debit Card   Delivered    TRK88559278            6       None          Email     1709.80
ORD200632 2023-05-02 00:00:00     C67260  Laptop         5     678.16     463 Main St     Gift Card   Delivered    TRK38229104            7   WINTER15       Facebook     3390.80
ORD200634 2024-04-25 00:00:00     C66906 Printer         2     259.32     117 Main St     Gift Card   Delivered    TRK31633755            2   WINTER15       Referral      518.64

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200004,2025-05-08 00:00:00,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
1,ORD200015,2023-07-17 00:00:00,C39416,Printer,1,473.96,942 Main St,Cash,Delivered,TRK54930938,3,None,Google,473.96
2,ORD200021,2024-11-17 00:00:00,C99023,Monitor,4,342.95,569 Main St,Cash,Delivered,TRK52646983,6,None,Google,1371.80
3,ORD200024,2024-10-30 00:00:00,C17470,Laptop,2,230.95,956 Main St,Online,Delivered,TRK28775057,3,WINTER15,Referral,461.90
4,ORD200025,2024-07-24 00:00:00,C42577,Monitor,1,399.98,709 Main St,Debit Card,Delivered,TRK69423327,3,WINTER15,Email,399.98
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,ORD201166,2023-07-31 00:00:00,C95568,Chair,3,324.47,971 Main St,Cash,Delivered,TRK37075292,4,WINTER15,Email,973.41
227,ORD201168,2023-04-08 00:00:00,C89559,Laptop,2,331.42,297 Main St,Credit Card,Delivered,TRK82838108,6,WINTER15,Google,662.84
228,ORD201171,2023-08-28 00:00:00,C39911,Phone,4,518.40,699 Main St,Credit Card,Delivered,TRK80431998,7,SAVE10,Facebook,2073.60
229,ORD201187,2024-03-13 00:00:00,C26340,Desk,2,184.60,562 Main St,Gift Card,Delivered,TRK59962703,7,WINTER15,Email,369.20
230,ORD201197,2023-07-13 00:00:00,C79674,Tablet,2,436.84,275 Main St,Online,Delivered,TRK88039356,2,FREESHIP,Instagram,873.68

Only 231 out of 1,200 orders are Delivered — just 19.25% of all orders.
The majority of orders are still Pending, Shipped, Cancelled, or Returned,
which means the business is successfully completing less than 1 in 5 orders.

In [ ]:
run_query("""SELECT OrderID, CustomerID, Product, TotalPrice
FROM orders
WHERE PaymentMethod = 'Credit Card' AND OrderStatus = 'Cancelled'""")

  OrderID CustomerID Product  TotalPrice
ORD200002     C81728  Tablet     2753.40
ORD200083     C15681  Laptop     2161.64
ORD200089     C17181 Printer     2276.65
ORD200103     C62656   Phone      873.72
ORD200106     C73514    Desk     1395.15
ORD200116     C47761 Printer     1165.40
ORD200147     C46316  Laptop      930.36
ORD200148     C35100   Phone      639.82
ORD200159     C48965 Printer      299.35
ORD200161     C35091 Monitor      211.14
ORD200202     C36938 Monitor      761.94
ORD200212     C53215 Monitor      265.38
ORD200228     C57867   Chair     1543.68
ORD200257     C89732   Phone      406.22
ORD200266     C38840   Chair     2332.28
ORD200275     C80735   Chair      130.14
ORD200355     C18353  Tablet     1299.99
ORD200365     C56796   Phone      678.38
ORD200368     C85322 Monitor      813.06
ORD200472     C60029   Chair     1524.36
ORD200527     C27202   Chair     3267.35
ORD200564     C93309    Desk     1821.40
ORD200594     C40140   Phone      363.20
ORD200616     C43919  Tablet     1804.80
ORD200642     C15063   Chair      426.10
ORD200645     C82990  Laptop      300.10
ORD200666     C35711 Monitor     1308.48
ORD200676     C90431  Laptop      844.68
ORD200682     C50274 Monitor     1528.26
ORD200688     C20077 Monitor     2372.88
ORD200758     C69021  Tablet     1874.52
ORD200764     C35983  Laptop     3137.15
ORD200774     C29701   Chair       61.62
ORD200810     C23637  Tablet      553.56
ORD200812     C81547   Phone      510.52
ORD200818     C25580   Phone     1563.36
ORD200836     C31810   Phone      178.44
ORD200889     C36725 Monitor     3253.60
ORD200908     C35117    Desk     1395.86
ORD200931     C14005 Printer       80.46
ORD200938     C39017   Chair      994.38
ORD200941     C91155 Printer      558.50
ORD200964     C18583   Phone     1822.10
ORD200966     C58503 Monitor     1402.60
ORD201010     C33729 Monitor     1978.71
ORD201021     C74519   Phone      945.81
ORD201039     C49137    Desk      598.46
ORD201077     C57861 Printer      915.48
ORD201132     C58858   Chair      674.64
ORD201140     C49838 Printer     1105.66
ORD201150     C17921    Desk     1210.60
ORD201178     C65107 Monitor       70.24
ORD201179     C84630  Laptop     2592.75
ORD201195     C21126    Desk      107.04

      OrderID CustomerID  Product  TotalPrice
0   ORD200002     C81728   Tablet     2753.40
1   ORD200083     C15681   Laptop     2161.64
2   ORD200089     C17181  Printer     2276.65
3   ORD200103     C62656    Phone      873.72
4   ORD200106     C73514     Desk     1395.15
5   ORD200116     C47761  Printer     1165.40
6   ORD200147     C46316   Laptop      930.36
7   ORD200148     C35100    Phone      639.82
8   ORD200159     C48965  Printer      299.35
9   ORD200161     C35091  Monitor      211.14
10  ORD200202     C36938  Monitor      761.94
11  ORD200212     C53215  Monitor      265.38
12  ORD200228     C57867    Chair     1543.68
13  ORD200257     C89732    Phone      406.22
14  ORD200266     C38840    Chair     2332.28
15  ORD200275     C80735    Chair      130.14
16  ORD200355     C18353   Tablet     1299.99
17  ORD200365     C56796    Phone      678.38
18  ORD200368     C85322  Monitor      813.06
19  ORD200472     C60029    Chair     1524.36
20  ORD200527     C27202    Chair     3267.35
21  ORD200564     C93309     Desk     1821.40
22  ORD200594     C40140    Phone      363.20
23  ORD200616     C43919   Tablet     1804.80
24  ORD200642     C15063    Chair      426.10
25  ORD200645     C82990   Laptop      300.10
26  ORD200666     C35711  Monitor     1308.48
27  ORD200676     C90431   Laptop      844.68
28  ORD200682     C50274  Monitor     1528.26
29  ORD200688     C20077  Monitor     2372.88
30  ORD200758     C69021   Tablet     1874.52
31  ORD200764     C35983   Laptop     3137.15
32  ORD200774     C29701    Chair       61.62
33  ORD200810     C23637   Tablet      553.56
34  ORD200812     C81547    Phone      510.52
35  ORD200818     C25580    Phone     1563.36
36  ORD200836     C31810    Phone      178.44
37  ORD200889     C36725  Monitor     3253.60
38  ORD200908     C35117     Desk     1395.86
39  ORD200931     C14005  Printer       80.46
40  ORD200938     C39017    Chair      994.38
41  ORD200941     C91155  Printer      558.50
42  ORD200964     C18583    Phone     1822.10
43  ORD200966     C58503  Monitor     1402.60
44  ORD201010     C33729  Monitor     1978.71
45  ORD201021     C74519    Phone      945.81
46  ORD201039     C49137     Desk      598.46
47  ORD201077     C57861  Printer      915.48
48  ORD201132     C58858    Chair      674.64
49  ORD201140     C49838  Printer     1105.66
50  ORD201150     C17921     Desk     1210.60
51  ORD201178     C65107  Monitor       70.24
52  ORD201179     C84630   Laptop     2592.75
53  ORD201195     C21126     Desk      107.04

Several Credit Card orders were cancelled. This is financially damaging
because cancelled Credit Card transactions may involve refund processing
costs. The business should investigate the reason behind these cancellations
to reduce revenue loss.

In [ ]:
run_query("""SELECT OrderID, Date, Quantity, UnitPrice, TotalPrice
FROM orders
WHERE Product = 'Laptop'""")

  OrderID                Date  Quantity  UnitPrice  TotalPrice
ORD200006 2025-06-17 00:00:00         1     664.42      664.42
ORD200013 2023-08-30 00:00:00         3     201.49      604.47
ORD200024 2024-10-30 00:00:00         2     230.95      461.90
ORD200026 2024-03-06 00:00:00         5      59.55      297.75
ORD200036 2025-05-08 00:00:00         2     534.43     1068.86
ORD200037 2024-10-14 00:00:00         2      76.74      153.48
ORD200038 2024-12-19 00:00:00         1     245.89      245.89
ORD200076 2024-03-31 00:00:00         4     382.88     1531.52
ORD200083 2023-08-22 00:00:00         4     540.41     2161.64
ORD200091 2023-03-15 00:00:00         5     492.75     2463.75
ORD200102 2023-03-08 00:00:00         2      70.34      140.68
ORD200108 2024-12-28 00:00:00         5      48.38      241.90
ORD200113 2024-01-17 00:00:00         5     190.08      950.40
ORD200122 2024-04-15 00:00:00         2     533.02     1066.04
ORD200129 2023-10-27 00:00:00         4     263.93     1055.72
ORD200134 2025-06-23 00:00:00         2     199.70      399.40
ORD200136 2024-04-27 00:00:00         1      44.35       44.35
ORD200147 2025-05-06 00:00:00         2     465.18      930.36
ORD200149 2023-12-27 00:00:00         1     217.56      217.56
ORD200179 2024-11-24 00:00:00         3     539.91     1619.73
ORD200185 2025-02-02 00:00:00         1     210.70      210.70
ORD200191 2025-03-08 00:00:00         2     488.87      977.74
ORD200197 2023-08-27 00:00:00         5     221.51     1107.55
ORD200198 2024-06-11 00:00:00         4     340.30     1361.20
ORD200204 2023-09-05 00:00:00         4     413.71     1654.84
ORD200206 2024-04-16 00:00:00         4     229.10      916.40
ORD200213 2023-04-20 00:00:00         1     634.40      634.40
ORD200219 2025-05-02 00:00:00         5      61.97      309.85
ORD200220 2023-07-18 00:00:00         2     373.17      746.34
ORD200245 2025-04-20 00:00:00         1     223.30      223.30
ORD200248 2023-07-02 00:00:00         1     670.54      670.54
ORD200278 2024-11-18 00:00:00         5     362.46     1812.30
ORD200283 2025-02-28 00:00:00         4     540.33     2161.32
ORD200284 2023-02-16 00:00:00         5     208.17     1040.85
ORD200288 2023-03-12 00:00:00         4     512.75     2051.00
ORD200305 2023-11-25 00:00:00         4     126.89      507.56
ORD200307 2023-07-01 00:00:00         3     557.41     1672.23
ORD200319 2023-12-02 00:00:00         2     563.06     1126.12
ORD200323 2025-01-26 00:00:00         1     150.17      150.17
ORD200326 2024-07-01 00:00:00         5     670.48     3352.40
ORD200336 2023-12-29 00:00:00         1      18.20       18.20
ORD200340 2023-04-23 00:00:00         5     521.25     2606.25
ORD200348 2024-03-13 00:00:00         3     359.73     1079.19
ORD200351 2025-02-15 00:00:00         1      64.66       64.66
ORD200357 2023-07-08 00:00:00         5     408.56     2042.80
ORD200363 2024-05-24 00:00:00         5     113.87      569.35
ORD200367 2024-04-25 00:00:00         5     658.77     3293.85
ORD200373 2023-01-02 00:00:00         3     341.15     1023.45
ORD200391 2025-01-16 00:00:00         2     527.46     1054.92
ORD200416 2023-07-18 00:00:00         2     644.05     1288.10
ORD200417 2023-10-24 00:00:00         5      55.41      277.05
ORD200425 2023-03-09 00:00:00         2     301.88      603.76
ORD200436 2023-02-11 00:00:00         4     221.33      885.32
ORD200446 2023-10-18 00:00:00         5     509.58     2547.90
ORD200448 2023-09-04 00:00:00         2     160.00      320.00
ORD200454 2024-11-27 00:00:00         1     109.29      109.29
ORD200460 2024-10-06 00:00:00         1     144.25      144.25
ORD200463 2023-05-26 00:00:00         5     662.78     3313.90
ORD200481 2023-04-23 00:00:00         4     484.85     1939.40
ORD200492 2023-10-25 00:00:00         5     606.52     3032.60
ORD200494 2023-07-19 00:00:00         3     505.79     1517.37
ORD200500 2024-04-07 00:00:00         5     508.59     2542.95
ORD200509 2023-02-15 00:00:00         2     425.03      850.06
ORD200519 2025-05-10 00:00:00         4     464.29     1857.16
ORD200532 2025-05-03 00:00:00         2      41.00       82.00
ORD200540 2024-01-29 00:00:00         5     648.65     3243.25
ORD200550 2023-10-29 00:00:00         4     228.91      915.64
ORD200551 2023-05-18 00:00:00         1     120.98      120.98
ORD200554 2025-05-30 00:00:00         2     492.90      985.80
ORD200556 2023-01-28 00:00:00         1     654.27      654.27
ORD200562 2023-10-06 00:00:00         3     663.93     1991.79
ORD200563 2023-12-12 00:00:00         1     132.68      132.68
ORD200568 2023-03-10 00:00:00         2     343.99      687.98
ORD200576 2024-05-29 00:00:00         5      79.08      395.40
ORD200581 2024-11-11 00:00:00         1     627.34      627.34
ORD200589 2025-02-10 00:00:00         2     500.80     1001.60
ORD200591 2024-11-18 00:00:00         1     605.28      605.28
ORD200606 2024-11-06 00:00:00         3     274.75      824.25
ORD200608 2024-07-24 00:00:00         5     543.16     2715.80
ORD200613 2024-12-19 00:00:00         2     230.36      460.72
ORD200619 2024-07-16 00:00:00         1     532.89      532.89
ORD200632 2023-05-02 00:00:00         5     678.16     3390.80
ORD200633 2024-04-10 00:00:00         5     601.72     3008.60
ORD200636 2023-10-05 00:00:00         4     371.07     1484.28
ORD200643 2024-08-26 00:00:00         1     438.37      438.37
ORD200645 2023-01-02 00:00:00         2     150.05      300.10
ORD200662 2023-01-28 00:00:00         3     438.89     1316.67
ORD200664 2024-12-19 00:00:00         4     194.75      779.00
ORD200667 2023-05-03 00:00:00         1     466.42      466.42
ORD200674 2024-01-09 00:00:00         4     358.75     1435.00
ORD200676 2025-06-23 00:00:00         2     422.34      844.68
ORD200691 2024-11-24 00:00:00         3     239.08      717.24
ORD200698 2023-01-04 00:00:00         2     388.22      776.44
ORD200699 2023-11-13 00:00:00         3     614.15     1842.45
ORD200700 2024-09-25 00:00:00         2      92.91      185.82
ORD200710 2024-07-22 00:00:00         5      21.54      107.70
ORD200714 2023-04-21 00:00:00         1      51.73       51.73
ORD200718 2023-04-08 00:00:00         4      64.74      258.96
ORD200719 2024-01-21 00:00:00         2     681.06     1362.12
ORD200726 2024-10-25 00:00:00         4     583.02     2332.08
ORD200732 2025-03-07 00:00:00         1     132.05      132.05
ORD200742 2024-11-30 00:00:00         3     699.93     2099.79
ORD200749 2025-04-13 00:00:00         1     518.39      518.39
ORD200763 2023-04-06 00:00:00         1     569.96      569.96
ORD200764 2024-03-10 00:00:00         5     627.43     3137.15
ORD200765 2023-10-06 00:00:00         2     534.91     1069.82
ORD200778 2023-04-28 00:00:00         4     246.85      987.40
ORD200780 2024-03-31 00:00:00         4     184.48      737.92
ORD200784 2025-05-16 00:00:00         1     325.81      325.81
ORD200790 2024-09-14 00:00:00         4     417.89     1671.56
ORD200795 2024-11-20 00:00:00         4     115.77      463.08
ORD200797 2023-02-27 00:00:00         2     438.76      877.52
ORD200799 2023-04-16 00:00:00         4     328.56     1314.24
ORD200805 2024-10-15 00:00:00         5     472.01     2360.05
ORD200811 2023-11-05 00:00:00         2      28.55       57.10
ORD200813 2025-03-15 00:00:00         5     292.54     1462.70
ORD200821 2024-12-14 00:00:00         4     174.49      697.96
ORD200823 2024-10-07 00:00:00         4     653.13     2612.52
ORD200842 2025-05-07 00:00:00         3     364.14     1092.42
ORD200851 2023-12-12 00:00:00         1     365.57      365.57
ORD200854 2025-06-13 00:00:00         3     372.60     1117.80
ORD200875 2023-08-03 00:00:00         5     133.39      666.95
ORD200880 2025-03-12 00:00:00         4     233.70      934.80
ORD200885 2024-04-07 00:00:00         4     515.59     2062.36
ORD200888 2024-07-23 00:00:00         2     266.95      533.90
ORD200890 2023-08-11 00:00:00         3     439.53     1318.59
ORD200897 2024-09-03 00:00:00         4     481.48     1925.92
ORD200900 2025-02-07 00:00:00         5      73.83      369.15
ORD200905 2023-11-23 00:00:00         1     442.39      442.39
ORD200915 2024-02-16 00:00:00         4     502.99     2011.96
ORD200917 2025-01-20 00:00:00         5     383.82     1919.10
ORD200918 2025-06-24 00:00:00         5     368.25     1841.25
ORD200927 2023-02-14 00:00:00         4      64.69      258.76
ORD200928 2024-05-09 00:00:00         3     247.11      741.33
ORD200932 2023-03-26 00:00:00         2      72.39      144.78
ORD200934 2025-06-01 00:00:00         4     119.84      479.36
ORD200939 2025-04-16 00:00:00         2     521.40     1042.80
ORD200944 2024-12-16 00:00:00         2     426.22      852.44
ORD200950 2024-05-31 00:00:00         1     596.24      596.24
ORD200960 2023-12-11 00:00:00         3     379.07     1137.21
ORD200965 2025-06-18 00:00:00         4     578.28     2313.12
ORD200972 2024-06-09 00:00:00         1      90.27       90.27
ORD200986 2024-09-07 00:00:00         4     644.96     2579.84
ORD200989 2023-03-23 00:00:00         4     246.11      984.44
ORD200997 2023-11-27 00:00:00         3     444.75     1334.25
ORD201013 2025-04-26 00:00:00         4     300.56     1202.24
ORD201018 2023-07-08 00:00:00         3     182.48      547.44
ORD201023 2024-09-23 00:00:00         5     233.67     1168.35
ORD201027 2024-05-21 00:00:00         4     554.83     2219.32
ORD201035 2023-11-12 00:00:00         4     506.11     2024.44
ORD201045 2024-09-20 00:00:00         5     316.40     1582.00
ORD201050 2023-08-20 00:00:00         5      69.70      348.50
ORD201057 2024-09-24 00:00:00         3     428.88     1286.64
ORD201061 2025-01-29 00:00:00         5     131.70      658.50
ORD201064 2025-02-12 00:00:00         4     198.81      795.24
ORD201068 2024-08-03 00:00:00         1     133.39      133.39
ORD201076 2023-05-08 00:00:00         4     686.61     2746.44
ORD201080 2023-01-20 00:00:00         5     464.74     2323.70
ORD201087 2025-03-23 00:00:00         4     693.07     2772.28
ORD201091 2024-10-08 00:00:00         3     209.48      628.44
ORD201092 2023-08-21 00:00:00         5     209.20     1046.00
ORD201099 2024-09-19 00:00:00         2     125.23      250.46
ORD201100 2023-08-17 00:00:00         5      38.11      190.55
ORD201103 2023-04-24 00:00:00         4     276.32     1105.28
ORD201108 2023-03-20 00:00:00         1     634.94      634.94
ORD201115 2025-06-20 00:00:00         2     336.32      672.64
ORD201119 2024-11-24 00:00:00         1     684.65      684.65
ORD201130 2025-02-16 00:00:00         2     323.45      646.90
ORD201156 2023-07-19 00:00:00         4     690.78     2763.12
ORD201163 2024-06-11 00:00:00         3     306.29      918.87
ORD201168 2023-04-08 00:00:00         2     331.42      662.84
ORD201179 2023-01-08 00:00:00         5     518.55     2592.75
ORD201184 2023-09-27 00:00:00         1     204.08      204.08

       OrderID                 Date  Quantity  UnitPrice  TotalPrice
0    ORD200006  2025-06-17 00:00:00         1     664.42      664.42
1    ORD200013  2023-08-30 00:00:00         3     201.49      604.47
2    ORD200024  2024-10-30 00:00:00         2     230.95      461.90
3    ORD200026  2024-03-06 00:00:00         5      59.55      297.75
4    ORD200036  2025-05-08 00:00:00         2     534.43     1068.86
..         ...                  ...       ...        ...         ...
168  ORD201156  2023-07-19 00:00:00         4     690.78     2763.12
169  ORD201163  2024-06-11 00:00:00         3     306.29      918.87
170  ORD201168  2023-04-08 00:00:00         2     331.42      662.84
171  ORD201179  2023-01-08 00:00:00         5     518.55     2592.75
172  ORD201184  2023-09-27 00:00:00         1     204.08      204.08

[173 rows x 5 columns]

Laptop unit prices range widely — from as low as $59.55 to $664.42 —
suggesting multiple laptop models at different price points. Some customers
purchase up to 5 units in a single order, indicating possible bulk or
business purchases.

***Sort with ORDER BY***

In [ ]:
run_query("""SELECT OrderID, Product, TotalPrice
FROM orders
ORDER BY TotalPrice DESC
LIMIT 10""")

  OrderID Product  TotalPrice
ORD200789  Tablet     3456.40
ORD201122 Monitor     3390.95
ORD200632  Laptop     3390.80
ORD200469   Chair     3384.90
ORD200328  Tablet     3370.20
ORD200107 Printer     3353.75
ORD200326  Laptop     3352.40
ORD201065 Printer     3334.00
ORD201031   Phone     3322.55
ORD200463  Laptop     3313.90

     OrderID  Product  TotalPrice
0  ORD200789   Tablet     3456.40
1  ORD201122  Monitor     3390.95
2  ORD200632   Laptop     3390.80
3  ORD200469    Chair     3384.90
4  ORD200328   Tablet     3370.20
5  ORD200107  Printer     3353.75
6  ORD200326   Laptop     3352.40
7  ORD201065  Printer     3334.00
8  ORD201031    Phone     3322.55
9  ORD200463   Laptop     3313.90

The highest value order is $3,456.40 for a Tablet. All top 10 orders
exceed $3,300 and include Tablets, Monitors, Laptops, Chairs, and Printers.
These high-value customers should be targeted for loyalty and retention
programs.

In [ ]:
run_query("""SELECT OrderID, Product, TotalPrice
FROM orders
ORDER BY TotalPrice ASC
LIMIT 10""")

  OrderID Product  TotalPrice
ORD201161   Phone       11.39
ORD200863   Phone       14.06
ORD200240  Tablet       17.24
ORD200542  Tablet       17.98
ORD200336  Laptop       18.20
ORD200776  Tablet       21.19
ORD201025   Chair       23.53
ORD200690 Monitor       24.48
ORD200926    Desk       26.95
ORD200473   Chair       29.86

     OrderID  Product  TotalPrice
0  ORD201161    Phone       11.39
1  ORD200863    Phone       14.06
2  ORD200240   Tablet       17.24
3  ORD200542   Tablet       17.98
4  ORD200336   Laptop       18.20
5  ORD200776   Tablet       21.19
6  ORD201025    Chair       23.53
7  ORD200690  Monitor       24.48
8  ORD200926     Desk       26.95
9  ORD200473    Chair       29.86

The lowest value order is just $11.39 for a Phone. The bottom 10 orders
are all under $30, likely representing single-unit purchases of budget
items or heavily discounted products using coupon codes.

In [ ]:
run_query("""SELECT OrderID, Date, Product, TotalPrice
FROM orders
WHERE OrderStatus = 'Delivered'
ORDER BY Date DESC""")

  OrderID                Date Product  TotalPrice
ORD200882 2025-06-28 00:00:00   Phone      548.24
ORD200226 2025-06-27 00:00:00    Desk     1764.15
ORD200918 2025-06-24 00:00:00  Laptop     1841.25
ORD200604 2025-06-22 00:00:00   Chair       97.86
ORD201044 2025-06-22 00:00:00 Printer       38.49
ORD200468 2025-06-21 00:00:00   Phone      418.36
ORD200583 2025-06-15 00:00:00   Chair      463.11
ORD200837 2025-06-14 00:00:00   Chair     3277.75
ORD200854 2025-06-13 00:00:00  Laptop     1117.80
ORD200285 2025-06-10 00:00:00   Phone      338.31
ORD200200 2025-06-07 00:00:00  Tablet     2166.30
ORD200870 2025-06-01 00:00:00   Phone     1880.36
ORD200140 2025-05-31 00:00:00   Chair     1584.42
ORD200261 2025-05-28 00:00:00   Phone      868.25
ORD201025 2025-05-17 00:00:00   Chair       23.53
ORD200508 2025-05-14 00:00:00   Phone      558.27
ORD200883 2025-05-13 00:00:00 Printer     2807.40
ORD201145 2025-05-12 00:00:00    Desk     1714.59
ORD200004 2025-05-08 00:00:00 Printer     2504.04
ORD200414 2025-05-04 00:00:00    Desk      279.14
ORD200532 2025-05-03 00:00:00  Laptop       82.00
ORD200219 2025-05-02 00:00:00  Laptop      309.85
ORD200395 2025-04-25 00:00:00   Phone      382.23
ORD200767 2025-04-18 00:00:00  Tablet      646.44
ORD200267 2025-04-17 00:00:00   Chair     2342.55
ORD200939 2025-04-16 00:00:00  Laptop     1042.80
ORD200172 2025-04-06 00:00:00 Printer      254.12
ORD200229 2025-03-28 00:00:00  Tablet      562.61
ORD200353 2025-03-28 00:00:00  Tablet      630.82
ORD200537 2025-03-23 00:00:00  Tablet      742.41
ORD200584 2025-03-21 00:00:00   Chair      580.20
ORD200207 2025-03-18 00:00:00   Phone      121.96
ORD200747 2025-03-12 00:00:00  Tablet      519.16
ORD201162 2025-03-11 00:00:00   Phone      448.74
ORD200732 2025-03-07 00:00:00  Laptop      132.05
ORD200166 2025-03-04 00:00:00   Chair      258.87
ORD200039 2025-02-27 00:00:00 Printer      769.38
ORD200730 2025-02-22 00:00:00   Phone      474.60
ORD200539 2025-02-18 00:00:00    Desk     1595.16
ORD200351 2025-02-15 00:00:00  Laptop       64.66
ORD200589 2025-02-10 00:00:00  Laptop     1001.60
ORD200196 2025-01-24 00:00:00    Desk      868.52
ORD200741 2025-01-23 00:00:00 Monitor     1663.20
ORD200648 2025-01-18 00:00:00 Monitor     1151.66
ORD200292 2025-01-15 00:00:00 Monitor       65.95
ORD200108 2024-12-28 00:00:00  Laptop      241.90
ORD201033 2024-12-24 00:00:00 Monitor      370.85
ORD200038 2024-12-19 00:00:00  Laptop      245.89
ORD200887 2024-12-19 00:00:00   Chair      514.98
ORD200510 2024-12-16 00:00:00 Printer      376.76
ORD200944 2024-12-16 00:00:00  Laptop      852.44
ORD200821 2024-12-14 00:00:00  Laptop      697.96
ORD200830 2024-12-11 00:00:00  Tablet      762.56
ORD200588 2024-12-10 00:00:00 Monitor     2311.28
ORD200210 2024-12-05 00:00:00   Chair     1075.44
ORD200137 2024-11-26 00:00:00 Monitor      501.96
ORD200179 2024-11-24 00:00:00  Laptop     1619.73
ORD201119 2024-11-24 00:00:00  Laptop      684.65
ORD200278 2024-11-18 00:00:00  Laptop     1812.30
ORD200021 2024-11-17 00:00:00 Monitor     1371.80
ORD200581 2024-11-11 00:00:00  Laptop      627.34
ORD200807 2024-11-10 00:00:00 Monitor     2028.63
ORD200156 2024-11-08 00:00:00   Chair      539.66
ORD200024 2024-10-30 00:00:00  Laptop      461.90
ORD200659 2024-10-26 00:00:00   Phone     1284.08
ORD200726 2024-10-25 00:00:00  Laptop     2332.08
ORD200304 2024-10-18 00:00:00 Monitor     2043.65
ORD200578 2024-10-10 00:00:00 Monitor     2830.35
ORD200752 2024-10-03 00:00:00   Phone     1717.48
ORD200029 2024-09-20 00:00:00    Desk     1270.59
ORD200841 2024-09-19 00:00:00 Printer      886.44
ORD200085 2024-09-09 00:00:00  Tablet      440.19
ORD200277 2024-09-09 00:00:00   Chair      454.60
ORD200970 2024-09-07 00:00:00    Desk      627.15
ORD200962 2024-09-06 00:00:00   Phone      284.16
ORD200897 2024-09-03 00:00:00  Laptop     1925.92
ORD201075 2024-08-31 00:00:00 Monitor     1105.26
ORD201017 2024-08-25 00:00:00   Chair     1361.70
ORD200214 2024-08-21 00:00:00    Desk     1222.88
ORD200078 2024-08-06 00:00:00 Printer      701.44
ORD200104 2024-07-30 00:00:00   Phone      582.04
ORD200772 2024-07-28 00:00:00 Monitor      604.87
ORD200715 2024-07-26 00:00:00 Printer     1960.89
ORD200025 2024-07-24 00:00:00 Monitor      399.98
ORD201126 2024-07-22 00:00:00   Phone      950.55
ORD200985 2024-07-20 00:00:00    Desk      243.71
ORD200558 2024-07-16 00:00:00   Phone     2512.48
ORD201083 2024-07-09 00:00:00   Chair      123.28
ORD200531 2024-07-02 00:00:00    Desk     1600.05
ORD200361 2024-06-29 00:00:00 Printer     3299.25
ORD200868 2024-06-29 00:00:00 Monitor     1265.28
ORD200994 2024-06-27 00:00:00  Tablet     2462.60
ORD200978 2024-06-25 00:00:00 Printer      429.96
ORD200701 2024-06-23 00:00:00 Monitor      276.66
ORD201079 2024-06-20 00:00:00   Phone     3170.00
ORD200322 2024-06-14 00:00:00   Phone     1159.10
ORD200739 2024-06-13 00:00:00   Phone     1546.92
ORD200744 2024-06-12 00:00:00  Tablet      922.74
ORD200972 2024-06-09 00:00:00  Laptop       90.27
ORD200096 2024-06-01 00:00:00   Phone      465.66
ORD200910 2024-05-31 00:00:00 Printer      926.94
ORD201157 2024-05-29 00:00:00 Monitor      904.65
ORD201006 2024-05-27 00:00:00  Tablet     2104.90
ORD200867 2024-05-26 00:00:00 Printer      570.32
ORD200291 2024-05-12 00:00:00   Phone      690.02
ORD200873 2024-05-12 00:00:00    Desk      410.52
ORD200996 2024-04-28 00:00:00 Monitor     1895.44
ORD200634 2024-04-25 00:00:00 Printer      518.64
ORD201095 2024-04-23 00:00:00   Phone      883.08
ORD201020 2024-04-22 00:00:00  Tablet       53.00
ORD200183 2024-04-18 00:00:00 Monitor      931.40
ORD200437 2024-04-18 00:00:00   Phone      512.39
ORD200174 2024-04-16 00:00:00 Printer     2403.24
ORD200793 2024-04-15 00:00:00   Chair      851.10
ORD200178 2024-04-11 00:00:00   Chair     2048.24
ORD200956 2024-04-11 00:00:00   Phone      321.96
ORD200169 2024-04-07 00:00:00 Printer      427.82
ORD200993 2024-04-06 00:00:00 Monitor      802.35
ORD200334 2024-03-26 00:00:00   Chair      899.00
ORD200061 2024-03-24 00:00:00    Desk      488.80
ORD200173 2024-03-24 00:00:00   Phone     1993.38
ORD200445 2024-03-23 00:00:00   Phone      487.21
ORD200926 2024-03-20 00:00:00    Desk       26.95
ORD200721 2024-03-18 00:00:00    Desk      237.18
ORD200787 2024-03-17 00:00:00    Desk      887.84
ORD200869 2024-03-17 00:00:00    Desk     1067.90
ORD200511 2024-03-15 00:00:00 Monitor     2876.20
ORD201187 2024-03-13 00:00:00    Desk      369.20
ORD200857 2024-03-10 00:00:00   Phone      773.52
ORD200026 2024-03-06 00:00:00  Laptop      297.75
ORD200145 2024-03-02 00:00:00 Printer      440.73
ORD200392 2024-02-28 00:00:00   Phone      627.20
ORD200757 2024-02-22 00:00:00    Desk      157.72
ORD200860 2024-01-23 00:00:00 Printer      422.54
ORD200624 2024-01-16 00:00:00  Tablet     1709.80
ORD200840 2024-01-14 00:00:00   Chair     1235.85
ORD200936 2024-01-12 00:00:00   Chair      226.64
ORD200781 2024-01-10 00:00:00   Phone     2621.30
ORD200674 2024-01-09 00:00:00  Laptop     1435.00
ORD201164 2024-01-08 00:00:00  Tablet     1577.85
ORD200548 2024-01-05 00:00:00 Printer     1278.36
ORD200804 2024-01-01 00:00:00   Chair      709.50
ORD200065 2023-12-30 00:00:00 Monitor      408.50
ORD201016 2023-12-29 00:00:00  Tablet     1343.90
ORD200149 2023-12-27 00:00:00  Laptop      217.56
ORD200254 2023-12-26 00:00:00 Monitor      789.57
ORD200230 2023-12-16 00:00:00    Desk      247.64
ORD200349 2023-11-30 00:00:00   Chair      465.33
ORD201054 2023-11-29 00:00:00 Printer      660.66
ORD200997 2023-11-27 00:00:00  Laptop     1334.25
ORD200935 2023-11-24 00:00:00   Phone     2078.13
ORD201040 2023-11-15 00:00:00  Tablet      536.07
ORD200580 2023-11-14 00:00:00 Monitor      511.98
ORD200385 2023-10-31 00:00:00   Chair      958.15
ORD200874 2023-10-31 00:00:00   Chair      977.80
ORD201065 2023-10-30 00:00:00 Printer     3334.00
ORD201055 2023-10-23 00:00:00 Monitor     1099.28
ORD200621 2023-10-22 00:00:00   Phone     2380.05
ORD200446 2023-10-18 00:00:00  Laptop     2547.90
ORD200717 2023-10-16 00:00:00   Chair      366.33
ORD200638 2023-10-15 00:00:00  Tablet     2313.08
ORD200980 2023-10-14 00:00:00   Chair      208.95
ORD201116 2023-10-14 00:00:00 Printer     1062.98
ORD201112 2023-10-13 00:00:00    Desk      356.81
ORD200413 2023-10-08 00:00:00  Tablet      118.80
ORD200845 2023-10-08 00:00:00   Phone      322.08
ORD200817 2023-10-05 00:00:00   Chair     2392.76
ORD200314 2023-10-04 00:00:00    Desk      612.36
ORD200309 2023-10-03 00:00:00   Chair     2199.04
ORD201030 2023-10-02 00:00:00   Phone      981.12
ORD200075 2023-09-26 00:00:00  Tablet     1194.51
ORD200090 2023-09-18 00:00:00   Chair      728.32
ORD201009 2023-09-02 00:00:00  Tablet      352.92
ORD201171 2023-08-28 00:00:00   Phone     2073.60
ORD201092 2023-08-21 00:00:00  Laptop     1046.00
ORD200040 2023-08-20 00:00:00    Desk      688.04
ORD200547 2023-08-20 00:00:00   Phone      613.98
ORD200789 2023-08-17 00:00:00  Tablet     3456.40
ORD200171 2023-08-15 00:00:00  Tablet      296.44
ORD201155 2023-08-13 00:00:00 Printer     2138.28
ORD200268 2023-08-11 00:00:00   Phone      847.76
ORD200875 2023-08-03 00:00:00  Laptop      666.95
ORD201166 2023-07-31 00:00:00   Chair      973.41
ORD200466 2023-07-18 00:00:00   Phone      432.47
ORD200015 2023-07-17 00:00:00 Printer      473.96
ORD200390 2023-07-14 00:00:00 Printer     2543.45
ORD201197 2023-07-13 00:00:00  Tablet      873.68
ORD200313 2023-07-09 00:00:00   Chair      868.60
ORD200357 2023-07-08 00:00:00  Laptop     2042.80
ORD201018 2023-07-08 00:00:00  Laptop      547.44
ORD200123 2023-07-06 00:00:00    Desk      834.12
ORD200769 2023-07-06 00:00:00 Printer     2714.20
ORD200307 2023-07-01 00:00:00  Laptop     1672.23
ORD200409 2023-06-28 00:00:00    Desk      420.65
ORD201000 2023-06-21 00:00:00 Printer     1304.65
ORD201098 2023-06-17 00:00:00 Monitor     1023.44
ORD200587 2023-06-12 00:00:00 Monitor     2573.00
ORD200259 2023-06-11 00:00:00   Chair     1740.48
ORD200359 2023-06-09 00:00:00    Desk     2426.28
ORD200704 2023-06-03 00:00:00    Desk      121.08
ORD200761 2023-06-02 00:00:00    Desk      151.04
ORD200979 2023-05-31 00:00:00 Monitor     2007.18
ORD200827 2023-05-25 00:00:00  Tablet     1279.76
ORD200551 2023-05-18 00:00:00  Laptop      120.98
ORD200650 2023-05-18 00:00:00    Desk      744.46
ORD200958 2023-05-13 00:00:00    Desk      475.98
ORD200290 2023-05-05 00:00:00   Chair      299.70
ORD200864 2023-05-03 00:00:00    Desk      491.11
ORD200632 2023-05-02 00:00:00  Laptop     3390.80
ORD200032 2023-05-01 00:00:00  Tablet     2683.60
ORD201026 2023-05-01 00:00:00 Monitor      677.48
ORD201103 2023-04-24 00:00:00  Laptop     1105.28
ORD200481 2023-04-23 00:00:00  Laptop     1939.40
ORD201032 2023-04-20 00:00:00   Chair      618.68
ORD200331 2023-04-15 00:00:00 Printer     1266.39
ORD201168 2023-04-08 00:00:00  Laptop      662.84
ORD200763 2023-04-06 00:00:00  Laptop      569.96
ORD200280 2023-03-27 00:00:00  Tablet     1213.86
ORD200932 2023-03-26 00:00:00  Laptop      144.78
ORD201113 2023-03-19 00:00:00    Desk      839.96
ORD200568 2023-03-10 00:00:00  Laptop      687.98
ORD200404 2023-03-09 00:00:00 Monitor      198.20
ORD200794 2023-03-09 00:00:00 Printer     1539.40
ORD200673 2023-02-21 00:00:00  Tablet      745.84
ORD200100 2023-02-17 00:00:00   Phone     1994.37
ORD200128 2023-02-17 00:00:00  Tablet       84.28
ORD200829 2023-02-05 00:00:00 Monitor       76.93
ORD200692 2023-01-23 00:00:00    Desk      984.20
ORD201080 2023-01-20 00:00:00  Laptop     2323.70
ORD201008 2023-01-13 00:00:00 Monitor     1232.64
ORD200698 2023-01-04 00:00:00  Laptop      776.44

       OrderID                 Date  Product  TotalPrice
0    ORD200882  2025-06-28 00:00:00    Phone      548.24
1    ORD200226  2025-06-27 00:00:00     Desk     1764.15
2    ORD200918  2025-06-24 00:00:00   Laptop     1841.25
3    ORD200604  2025-06-22 00:00:00    Chair       97.86
4    ORD201044  2025-06-22 00:00:00  Printer       38.49
..         ...                  ...      ...         ...
226  ORD200829  2023-02-05 00:00:00  Monitor       76.93
227  ORD200692  2023-01-23 00:00:00     Desk      984.20
228  ORD201080  2023-01-20 00:00:00   Laptop     2323.70
229  ORD201008  2023-01-13 00:00:00  Monitor     1232.64
230  ORD200698  2023-01-04 00:00:00   Laptop      776.44

[231 rows x 4 columns]

The most recent delivered order was on June 28, 2025 — a Phone worth
$548.24. Delivered orders include all product types with no single product
dominating, showing balanced delivery performance across categories.

***Aggregate with COUNT, SUM, AVG***

In [ ]:
run_query("SELECT COUNT(*) AS TotalOrders FROM orders")

 TotalOrders
        1200

   TotalOrders
0         1200

The dataset contains exactly 1,200 orders. This is a solid sample size
for drawing reliable business insights across all product categories,
payment methods, and order statuses.

In [ ]:
run_query("SELECT SUM(TotalPrice) AS TotalRevenue FROM orders")

 TotalRevenue
   1264761.96

   TotalRevenue
0    1264761.96

Total gross revenue across all 1,200 orders is $1,264,761.96. This
includes cancelled and returned orders, so actual collected revenue
is significantly lower than this figure.

In [ ]:
run_query("SELECT AVG(TotalPrice) AS AverageRevenue FROM orders")

 AverageRevenue
      1053.9683

   AverageRevenue
0       1053.9683

The average order value is $1,053.97. This relatively high average is
likely driven by customers purchasing multiple units per order of
electronics and furniture items.

In [ ]:
run_query("""SELECT SUM(TotalPrice) AS DeliveredRevenue
FROM orders
WHERE OrderStatus = 'Delivered'""")

 DeliveredRevenue
        242600.32

   DeliveredRevenue
0         242600.32

Only $242,600.32 out of $1,264,761.96 total revenue comes from Delivered
orders — just 19.2%. Over 80% of gross revenue is tied up in Pending,
Shipped, Cancelled, or Returned orders, which represents a significant
business risk.

***GROUP BY***

In [ ]:
run_query("""SELECT OrderStatus, COUNT(*) AS OrderCount
FROM orders
GROUP BY OrderStatus
ORDER BY OrderCount DESC""")

OrderStatus  OrderCount
  Cancelled         250
   Returned         247
    Pending         237
    Shipped         235
  Delivered         231

  OrderStatus  OrderCount
0   Cancelled         250
1    Returned         247
2     Pending         237
3     Shipped         235
4   Delivered         231

Result:
  Cancelled  250
   Returned  247
    Pending  237
    Shipped  235
  Delivered  231

Cancelled orders are the highest at 250, and Delivered orders are the
lowest at 231. The fact that more orders are cancelled than delivered is
a critical business problem that needs immediate attention.

In [ ]:
run_query("""SELECT Product, SUM(TotalPrice) AS TotalRevenue
FROM orders
GROUP BY Product
ORDER BY TotalRevenue DESC""")

Product  TotalRevenue
  Chair     195620.11
Printer     195612.61
 Laptop     192126.56
 Tablet     186568.95
Monitor     175651.41
   Desk     167459.93
  Phone     151722.39

   Product  TotalRevenue
0    Chair     195620.11
1  Printer     195612.61
2   Laptop     192126.56
3   Tablet     186568.95
4  Monitor     175651.41
5     Desk     167459.93
6    Phone     151722.39

Result:
  Chair    195,620.11
Printer    195,612.61
 Laptop    192,126.56
 Tablet    186,568.95
Monitor    175,651.41
   Desk    167,459.93
  Phone    151,722.39

Chair and Printer are virtually tied at the top with ~$195,000 each.
Revenue is fairly evenly spread across all 7 products — no single product
dominates, showing a well-diversified product portfolio.

In [ ]:
run_query("""
SELECT Product,
       COUNT(*) AS TotalOrders,
       SUM(TotalPrice) AS TotalRevenue,
       AVG(TotalPrice) AS AvgOrderValue
FROM orders
GROUP BY Product
ORDER BY TotalRevenue DESC
""")

Product  TotalOrders  TotalRevenue  AvgOrderValue
  Chair          178     195620.11    1098.989382
Printer          181     195612.61    1080.732652
 Laptop          173     192126.56    1110.558150
 Tablet          179     186568.95    1042.284637
Monitor          163     175651.41    1077.616012
   Desk          170     167459.93     985.058412
  Phone          156     151722.39     972.579423

   Product  TotalOrders  TotalRevenue  AvgOrderValue
0    Chair          178     195620.11    1098.989382
1  Printer          181     195612.61    1080.732652
2   Laptop          173     192126.56    1110.558150
3   Tablet          179     186568.95    1042.284637
4  Monitor          163     175651.41    1077.616012
5     Desk          170     167459.93     985.058412
6    Phone          156     151722.39     972.579423

Result:
Product  TotalOrders  TotalRevenue  AvgOrderValue
  Chair          178    195620.11        1098.99
Printer          181    195612.61        1080.73
 Laptop          173    192126.56        1110.56
 Tablet          179    186568.95        1042.28
Monitor          163    175651.41        1077.62
   Desk          170    167459.93         985.06
  Phone          156    151722.39         972.58

Laptop has the highest average order value at $1,110.56 despite not
having the most orders. Phone has both the fewest orders (156) and the
lowest average value ($972.58), making it the weakest performer overall.
Printer has the most orders at 181 but a lower average value than Laptop.

In [ ]:
run_query("""
SELECT ReferralSource, COUNT(*) AS OrderCount
FROM orders
GROUP BY ReferralSource
ORDER BY OrderCount DESC
""")

ReferralSource  OrderCount
     Instagram         259
         Email         250
        Google         241
      Facebook         228
      Referral         222

  ReferralSource  OrderCount
0      Instagram         259
1          Email         250
2         Google         241
3       Facebook         228
4       Referral         222

Result:
 Instagram  259
     Email  250
    Google  241
  Facebook  228
  Referral  222

Instagram is the top customer acquisition channel with 259 orders.
All 5 channels perform similarly with a narrow gap of only 37 orders
between the highest and lowest, suggesting a balanced multi-channel
marketing strategy.

In [ ]:
run_query("""SELECT PaymentMethod, AVG(TotalPrice) AS AvgOrderValue
FROM orders
GROUP BY PaymentMethod
ORDER BY AvgOrderValue DESC""")

PaymentMethod  AvgOrderValue
  Credit Card    1127.553974
    Gift Card    1070.973565
         Cash    1056.041829
       Online    1017.220698
   Debit Card    1001.556810

  PaymentMethod  AvgOrderValue
0   Credit Card    1127.553974
1     Gift Card    1070.973565
2          Cash    1056.041829
3        Online    1017.220698
4    Debit Card    1001.556810

Result:
Credit Card   1127.55
  Gift Card   1070.97
       Cash   1056.04
     Online   1017.22
 Debit Card   1001.56

Credit Card customers spend the most on average at $1,127.55, while
Debit Card customers spend the least at $1,001.56. The $126 gap suggests
Credit Card users tend to purchase higher-value items or larger quantities.

***HAVING***

In [ ]:
run_query("""SELECT Product, SUM(TotalPrice) AS TotalRevenue
FROM orders
GROUP BY Product
HAVING SUM(TotalPrice) > 50000
ORDER BY TotalRevenue DESC""")

Product  TotalRevenue
  Chair     195620.11
Printer     195612.61
 Laptop     192126.56
 Tablet     186568.95
Monitor     175651.41
   Desk     167459.93
  Phone     151722.39

   Product  TotalRevenue
0    Chair     195620.11
1  Printer     195612.61
2   Laptop     192126.56
3   Tablet     186568.95
4  Monitor     175651.41
5     Desk     167459.93
6    Phone     151722.39

All 7 products exceed $50,000 in total revenue, confirming every product
category is commercially strong. Chair leads at $195,620 and Phone is
lowest at $151,722 — but even the lowest product generates over 3x the
threshold, showing a healthy product lineup.

In [ ]:
run_query("""SELECT PaymentMethod, COUNT(*) AS UsageCount
FROM orders
GROUP BY PaymentMethod
HAVING COUNT(*) > 200""")

PaymentMethod  UsageCount
         Cash         246
  Credit Card         234
   Debit Card         232
    Gift Card         230
       Online         258

  PaymentMethod  UsageCount
0          Cash         246
1   Credit Card         234
2    Debit Card         232
3     Gift Card         230
4        Online         258

Result:
       Cash  246
Credit Card  234
 Debit Card  232
  Gift Card  230
     Online  258

All 5 payment methods are used more than 200 times each. Online is the
most frequently used at 258 transactions and Gift Card the least at 230.
The near-equal usage across all methods shows customers have no strong
preference — the business should continue supporting all payment options.